pipeline { 
  agent any 
  
  stages { 
     stage('clean workspace'){
        steps{ 
           cleanWs()
        }
     }

     stage('Checkout from Git'){
        steps{ 
           git branch: 'main', url : 'https://github.com/amitvashisttech/applicationtesting-sast-dast-aristocart-04-Jun-2024.git'
        }
     }

    
     stage('Maven CleanUP'){
        steps{ 
           sh 'mvn clean -f  03-Easybuggy/pom.xml'
        }
     }


     stage('Maven Compile'){
        steps{ 
           sh 'mvn compile -f  03-Easybuggy/pom.xml'
        }
     }

     stage('Maven Package'){
        steps{ 
           sh 'mvn package -f  03-Easybuggy/pom.xml'
        }
     }


     stage('Archive Artifacts - JAR'){
        steps{ 
           archive '03-Easybuggy/target/*.jar'
        }
     }


     stage('Docker Build'){
        steps{ 
           sh "cd 03-Easybuggy"
           sh "docker build -t easybuggy -f Dockerfile ."
           sh "docker tag easybuggy amitvashist7/easybuggy:latest" 
        }
     }


  }

}
